export default function TermsDesc(){
    return(
        <section className="px-4 flex flex-col 
        lg:flex-row gap-10 md:px-8 lg:px-12 py-8 lg:py-10 bg-[#FAF7F4] w-full h-auto min-h-screen">
            {/* Sidebar navigation made sticky so it stays visible while scrolling */}
            <aside className="flex flex-col items-start gap-3 lg:w-64 lg:sticky lg:top-10 h-fit">
               <span className="text-[#9C9A99] text-[11px] uppercase leading-[17px] font-inter font-semibold tracking-wider">
                    on this page
                </span> 
                <div className="flex flex-col items-start gap-2.5 pl-4 h-auto border-l border-l-[#999794]">
                  {/* 1. Changed to <a> tags with href instead of plain <p> with bad IDs */}
                  <a 
                    href="#whoYouAre" 
                    className="text-[14px] font-inter text-[#6D6A67] hover:text-[#252423] transition-colors text-left"
                  >
                    Who "you" are
                  </a>
                  <a 
                    href="#whoWeAre" 
                    className="text-[14px] font-inter text-[#6D6A67] hover:text-[#252423] transition-colors text-left"
                  >
                    Who we are and what we do (and what we don't do)
                  </a>
                  <a href="#service"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                        use of the Services: Accounts
                  </a>
                    <a href="#disclosure"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                        Disclosure Materials: License
                  </a>
                
                    <a href="yourMaterialsLicense"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                       Your Materials: License
                  </a>
                     <a href="paidServices"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                      Paid Services
                  </a>
                   
                     <a href="sellers"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                      Sellers
                  </a>
                
                     <a href="buyer"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                      Buyer Obligations, Representations and Warranties
                  </a>
                  
                     <a href="market"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                      Marketplace Disclaimers, Informational Tools, and Third Party Services
                  </a>
                       <a href="fee"
                    className="pl-4 text-[12px] leading-[16px] text-[#6D6A67]
                     hover:text-[#252423] transition-colors text-left">
                      Compensation and Referral Fee Disclosure

                  </a>
                </div>
            </aside>
            
            <main className="flex-1 flex flex-col items-start gap-4 w-full">
                 <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">These Terms of Service (the “Terms”) constitute a legally binding contract between you and BizScout LLC and govern your access to and use of our website, products, services, and applications (collectively, the “Services”) and may incorporate additional order forms, policies, and terms applicable to your participation in the Services.</p>
                 <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">PLEASE NOTE THAT SECTION 15 CONTAINS AN ARBITRATION CLAUSE AND CLASS ACTION WAIVER. By using our Services, you agree to resolve disputes with BizScout through binding individual arbitration, which means that you waive any right to have those disputes decided by a judge or jury, and that you waive your right to participate in class actions, class arbitrations, or representative actions</p>
                 <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">Please read these Terms carefully. By using our Services or clicking “I agree” or likewise expressing your assent, you indicate you have read and understood these Terms and are bound by them.</p>
                 
                 {/* 2. Fixed target ID format (removed the #) and changed to a semantic element block */}
                 <h2 id="whoYouAre" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Who "you" are
                 </h2>
                 <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">We look forward to getting to know you better! But, for now, “you” shall mean the person, business, or legal entity, that uses any of our Services. For the sake of clarity, each of the following is included in the term “you”: </p>
                 <ul className="list-disc list-inside pl-4 flex flex-col items-start gap-2.5 text-[16px] leading-[24px] font-inter font-light text-[#252423]">
    <li>a user of our Services that does not create an account with BizScout;</li>
    <li>a user of our Services that creates an account and accesses listings or other information through the Services (a “Buyer”);</li>
    <li>a user of our Services that submits information regarding an opportunity to acquire business assets (a “Seller”).</li>
</ul>
             <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">When we use the words “user” or “you” in these Terms, they refer to all of the above, regardless of whether you are just viewing our site or are a Buyer or a Seller. If we use one of those specific terms, it only applies to that category of user. </p>
            
            <span className="text-[#252423] font-inter font-medium text-[16px] leading-[24px]">By using the Services you represent and warrant that you (i) are at least 18 years old; (ii) have read and understand these Terms; (iii) have the right, authority and capacity to enter into and shall abide by these Terms.</span>
            <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">If you are accessing the Services for or on behalf of a business or legal entity (an "Organization"), "you" also includes the Organization for which you act, and your Organization is legally and financially responsible for your access to and use of the Services as well as for the use of the Services by others affiliated with the Organization, including any employees, agents, contractors, or customers. If you are accessing the Services on behalf of an Organization, 
                <span className="font-medium">you additionally represent and warrant that you (i) have full legal authority 
                    to bind the Organization to these Terms; (ii) you have read and understand these Terms; 
                    and (ii) agree to these Terms on behalf of the Organization.</span> </p>
               <h2 id="whoWeAre" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Who we are and what we do (and what we don't do)
                 </h2>
                 <p className="text-[16px] leading-[24px] font-inter font-light text-[#252423]">We are BizScout LLC ("BizScout" or "we", "us" and "our"). We operate the BizScout marketplace (the “Marketplace”) which allows third-party sellers to list opportunities to acquire business assets (each, a “Business Listing”) and connect with interested third-party buyers using our Services).

We do a lot, but not everything. You hereby acknowledge and agree that BizScout does not engage in any of the following and accordingly accept all related responsibilities:</p>
            <ol className="list-decimal pl-5 flex flex-col items-start gap-2.5 text-[16px] leading-[24px] font-inter font-light text-[#252423]">
    <li>BizScout does not sell or offer to sell companies, their assets, or related opportunities, buy or offer to buy companies, their assets, or related opportunities, solicit prospective sellers or buyers of companies, their assets, or related opportunities, or negotiate the purchase, sale, or exchange of companies, their assets, or related opportunities.</li>
    <li>Unless BizScout has entered into a separate written agreement with you, explicitly establishing an agent-principal relationship, BizScout does not act as your representative in any capacity when you use the Services. Your use of the Services does not create, either expressly or implicitly, any fiduciary duty, attorney-client relationship, agency, or other form of representation. BizScout does not act as your attorney, broker, fiduciary, or agent, nor does it engage in negotiations on your behalf.</li>
    <li>BizScout is not a law firm, and its Services do not provide or constitute legal advice. BizScout does not offer legal analysis or representation. Any information provided through the Services, including by BizScout employees or contractors, is strictly for informational purposes and should not be considered legal advice.</li>
    <li>BizScout is not responsible for any closing-related tasks, including with respect to taxes, notifications, and regulatory filings. All closing-related tasks are solely your responsibility.</li>
    <li>While BizScout may seek to connect you with Referral Partners (defined below), BizScout makes no representations, warranties, or guarantees regarding any Referral Partners or the services they provide and is not a party to any agreements you may elect to have with Referral Partners.</li>
    <li>BizScout performs no technical, legal, financial, or any other kind of due diligence related to Business Listings, buyers, sellers, or other participants in the Marketplace and makes no representations, warranties, or guarantees regarding Business Listings, buyers, sellers, or participants of any kind. You are solely and exclusively responsible for performing all due diligence.</li>
    <li>BizScout is not a party to any transaction agreement among buyers and sellers in connection with a Business Listing; provided that, BizScout shall be deemed a third-party beneficiary to any Consummated Transaction for the purposes of payment of applicable Marketing Fees.</li>
    <li>BizScout does not engage in dispute resolution between or among buyers, sellers, and Referral Partners in connection with the Marketplace.</li>


</ol>
 <h2 id="service" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                 Use of the Services; Accounts
                 </h2>
                 <ol className="list-decimal
                  pl-5 flex flex-col items-start
                   gap-2.5 text-[16px] leading-[24px] font-inter font-light text-[#252423]">
                    <li>Provision of Access. Subject to and conditioned on your compliance with these Terms, we hereby grant you a non-exclusive, non-transferable, revocable right to access and use the Services for your internal use.</li>
                    <li>Use Restrictions. You shall not use the Services for any purposes beyond the scope of the access granted in these Terms. You shall not at any time, directly or indirectly, (i) copy, modify, adapt, alter or create derivative works of the Services, including the listings provided therein, in whole or in part; (ii) rent, lease, lend, sell, license, sublicense, assign, distribute, publish, transfer, or otherwise make available the Services, including the listings provided therein; (iii) reverse engineer, disassemble, decompile, decode, adapt, or otherwise attempt to derive or gain access to any software component of the Services, in whole or in part; (iv) use automated tools, scripts, or any unauthorized methods to extract data from the Services; (v) remove any proprietary notices from the Services; (vi) use or access the Services to build or support, and/or assist any third party in building or supporting, products, or services competitive to the Services; (vii) take any action that could disrupt, damage, or impair the functionality of the Services, including introducing viruses, malware, or harmful code; or (viii) use the Services in any manner or for any purpose that infringes, misappropriates, or otherwise violates any intellectual property right or other right of any person, or that violates any applicable law.</li>
                    <li>Prohibited Use and Transactions. You agree that you will not, and will not assist or permit any third party to: (i) sell, advertise, solicit, engage in, or broker securities transactions, as the term security is defined in the Securities Act of 1933, as amended (a “Security” or “Securities”), in violation of securities laws and regulations; (ii) list or engage in the sale or transfer of any businesses, assets, or Securities that violate applicable laws, regulations, or BizScout’s policies; (iii) engage in, promote, or facilitate any illegal activities or business practices, including but not limited to fraudulent misrepresentations, Ponzi schemes, or unfair or deceptive trade practices; (iv) engage in unauthorized advertising, solicitation, or promotional activities within the Marketplace, including but not limited to direct marketing, spam, or offering services outside of uses permitted by BizScout; or (v) circumvent, interfere with, or attempt to bypass BizScout’s fees, security features, and policies, including by negotiating or closing transactions outside the Marketplace.</li>
                    <li>Your Account; Provided Information. In order to use some of the Services, you will be required to create an account, select a password and user name, and provide us with certain information or data, including your contact information and payment information ("Account Data"). You may not share or transfer your account to anyone else without our prior written permission. You promise to provide us with accurate, complete, and updated Account Data. You may not select as your BizScout account name a name that you do not have the right to use, or another person’s name with the intent to impersonate that person. You may not transfer your account to anyone else without our prior written permission and any attempt to do so will result in termination of your account with us. BizScout is entitled to rely upon all information you provide to us in connection with your Account Data and your use of the Services, and you represent and warrant that all such information is and will remain accurate, complete, and not misleading.</li>
                    
                   </ol>
 <h2 id="disclosure" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                  Disclosure Materials; Non-Disclosure
                 </h2>
                 <ol className="list-decimal flex flex-col items-start pl-5 gap-2.5 text-[16px] leading-[24px]
                  font-inter font-light text-[#252423]">
                    <li>As used in these Terms, “Disclosure Materials” includes any information concerning a Business Listing disclosed by, or on behalf of, a user of the Services (“Provider”) that is furnished or otherwise made available to a user of the Services (“Recipient”) or its Representatives in connection with the Recipient’s evaluation of a potential transaction involving the Provider (a “Potential Transaction”). This includes, without limitation, any technical, business, financial, legal, or operational information, as well as any notes, analyses, summaries, forecasts, compilations, or other materials prepared by or on behalf of the Recipient that are based on, reflect, or incorporate such information in whole or in part. Disclosure Materials does not include information that: (i) becomes publicly available other than through a breach of these Terms by the Recipient or its Representatives; (ii) was lawfully in the Recipient’s possession prior to disclosure by or on behalf of the Provider, without breach of any confidentiality obligation; or (iii) is disclosed to the Recipient on a non-confidential basis by a third party lawfully in possession of such information and not subject to an obligation of confidentiality to the Provider. “Representatives” shall include the directors, officers, employees, agents, partners or advisors (including, without limitation, attorneys, accountants, consultants, bankers and financial advisors) of the Recipient or Provider, as applicable.</li>
                    <li>Each Recipient shall, and shall ensure its Representatives, use the Disclosure Materials solely for the purpose of evaluating a Potential Transaction, and shall keep such Disclosure Materials strictly confidential. Neither the Recipient nor its Representatives shall disclose any Disclosure Materials in any manner whatsoever; provided, however, that Disclosure Materials may be disclosed to those of the Recipient's Representatives who need to know such information for the sole purpose of assisting the Recipient in evaluating the Potential Transaction and who are informed of the confidential nature of such information. Upon concluding their evaluation if a Potential Transaction is not pursued, or as may be otherwise agreed in writing between the Provider and Recipient, Recipients agree to promptly and securely delete or destroy all Disclosure Materials (including all copies and derivatives thereof) or, if requested by the Provider, return such materials. Each Recipient agrees to be fully responsible and liable for any breach of these Terms by any of its Representatives. These Terms do not grant a Recipient or any of its Representatives any license to use the Provider's Disclosure Materials other than for the specific purpose of evaluating a Potential Transaction as expressly permitted herein.</li>
                    <li>Each Recipient agrees that, without the prior written consent of Provider, each Recipient will not, and it will cause its Representatives not to, disclose to any person or entity (i) that Disclosure Materials have been exchanged between the Provider and Recipient, (ii) that discussions or negotiations are taking place between Provider and Recipient concerning a Potential Transaction or (iii) any of the terms, conditions or other facts with respect thereto (including the status thereof).</li>
                    <li>Users acknowledge that BizScout may provide such Disclosure Materials for the purpose of providing the Services. BizScout agrees that it shall treat Provider’s Disclosure Materials as confidential and shall not disclose such Disclosure Materials to any third party, except: (i) BizScout may provide such Disclosure Materials for the purposes of providing the Services; (ii) BizScout may disclose the Disclosure Materials to its Representatives in connection with the Services; and (iii) in the event that BizScout is required to disclose any Disclosure Materials, and, when possible pursuant to statutory or regulatory authority, BizScout will provide such Provider with prompt written notice so that the Provider may seek a protective order or waive compliance by BizScout with the provisions of these Terms. If, in the absence of a protective order or the receipt of a waiver hereunder, BizScout is nonetheless, on the advice of its counsel, legally required to disclose the Disclosure Materials, BizScout may disclose such information without liability hereunder.</li>
                 </ol>
                 <h2 id="yourMaterialsLicense" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                Your Materials; License
                 </h2>
                 <ol className="list-decimal flex flex-col items-start pl-5 gap-2.5 text-[16px] leading-[24px]
                  font-inter font-light text-[#252423]">
                    <li>Your Materials. You are solely responsible for: (i) all materials, information, images, videos, data, contact information, and other content provided to BizScout in connection with a Business Listing, your profile, or otherwise, whether or not created originally by you ("Your Content"); and (ii) all websites and content linked or otherwise referenced in Your Content (the "Linked Content" and, together with Your Content, "Your Materials"). For Sellers, Your Content includes all information provided to BizScout for use in preparing and publishing a Business Listing on Seller's behalf.</li>
                    <li>License. You hereby grant to BizScout a limited, royalty-free, perpetual, irrevocable, non-exclusive, fully sublicensable right and license to copy, modify, display, distribute, perform, create derivative works from, store and otherwise use and exploit, all Your Content, in any form through any media, software, or technology, in connection with: (a) providing you the Services; (b) distributing Your Content through or in connection with the Services or through BizScout’s authorized third-party partners and licensees and as further described in our Privacy Policy. BizScout makes no claim to any ownership interest in Your Content obtained from you under these Terms, and no ownership rights will be transferred under these Terms. BizScout shall be permitted to use and aggregate non-personally identifiable information for internal and commercial purposes, and nothing herein shall prevent BizScout from using information that is already in the public domain.</li>
                    <li>Representation and Warranties. You represent and warrant that (i) you have the right to provide Your Materials; (ii) you are legally permitted to grant BizScout the license set forth in this Section; (iii) the use of Your Materials in connection with the Services will not infringe the rights of any third-party, including without limitation, any privacy rights, publicity rights, copyrights, moral rights, trademark rights, contract rights, confidentiality obligations, or any other intellectual property or proprietary rights; (iv) Your Content does not violate, facilitate, or encourage violation of any applicable law; and (v) Your Content is not misleading, intentionally or negligently fraudulent and is true and correct in all respects as of the date of its disclosure. For the avoidance of doubt, Seller's representations and warranties regarding Your Content apply to all information provided by Seller to BizScout, and Seller remains fully responsible for the accuracy and completeness of such information notwithstanding that BizScout prepares and publishes the Business Listing on Seller's behalf.</li>
                  
                  </ol>
                   <h2 id="paidServices" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Paid Services
                     </h2>
                 <ol className="list-decimal flex flex-col items-start pl-5 gap-2.5 text-[16px] font-light font-inter
                  leading-[24px] text-[#252423]">
                    <li>Subscription Services. When you make a purchase using the Services, you agree to all written terms and conditions applicable to such purchase. The Services may include certain subscription-based plans with automatically recurring payments for periodic charges (“Subscription Service”) beginning on the date of your purchase (“Subscription Billing Date”). The Subscription Service will continue for the subscription period that you select (“Initial Subscription Period”), and upon the expiration of such Initial Subscription Period will automatically renew for successive periods of the same duration as the Initial Subscription Period (the Initial Subscription Period, together with each such renewal period, the “Subscription Period”) unless you cancel the Subscription Service as set forth below or we terminate it.</li>
                    <li>Billing. If you activate a Subscription Service, then you authorize us or our third-party payment processors to periodically charge, on a going-forward basis and until cancellation of the Subscription Service, all accrued sums on or before the payment due date. Your account will be charged automatically on the Subscription Billing Date and thereafter on the renewal date of your Subscription Service for all applicable fees and taxes for the next Subscription Period. BizScout reserves the right to change the fees for any Subscription Service at any time. BizScout will provide you with reasonable prior notice of any changes to such fees before they become effective, and such changes will apply to the applicable Subscription Service upon the next Subscription Period renewal following such notice. Your continued use of the Subscription Service thereafter constitutes your agreement to pay the modified fee; if you do not agree to the new fee, you must cancel the applicable Subscription Service as provided herein before such renewal.</li>
                    <li>Cancellation; No Refunds. You must cancel your Subscription Service before it renews in order to avoid the charge to your account of the next periodic Subscription Fee. You may cancel the Subscription Service by doing so online or contacting us at support@bizscout.com. We must receive your cancellation request before the applicable renewal date in order to avoid the charge for the next Subscription Period.</li>
                    <li>Payment Processing. We may contract with a third party to process any payments submitted for or through our Services (“Payment Processor”). By making any purchase through the Services, you authorize us to share any of your information with the Payment Processor in order to process your payment.</li>
                    <li>Authorization. You authorize us to charge all sums for all amounts due under these Terms, including all applicable taxes, to the payment method specified in your account</li>
                    <li>Delinquent Accounts. BizScout may suspend or terminate access to the Service, including fee-based portions of the Services, for any account for which any amount is due but unpaid. In addition to the amount due for the Services, a delinquent account will be charged with fees or charges that are incidental to any chargeback or collection of any the unpaid amount, including collection fees.</li>
                  </ol>
                   <h2 id="sellers" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Sellers
                     </h2>
                 <ol className="list-decimal flex flex-col items-start pl-5 gap-2.5 text-[16px] font-light font-inter
                  leading-[24px] text-[#252423]">
                     <li>Listing Process. Seller acknowledges and agrees that the process for listing a business on the Marketplace is as follows: (i) Seller provides BizScout with information regarding the business opportunity, including financial data, business descriptions, images, and other relevant materials; (ii) BizScout reviews, prepares, and formats a Business Listing based on Seller's information; (iii) BizScout publishes the Business Listing on the Marketplace at Seller's direction; and (iv) Seller reviews the published Business Listing and promptly notifies BizScout of any errors or required changes. Seller retains sole responsibility for the accuracy of all information provided to BizScout, and BizScout's preparation and publication of the Business Listing does not constitute verification, endorsement, or adoption of the information contained therein.</li>
                     <li>Listing Content. Seller may provide information to BizScout for the purpose of creating a Business Listing on the Marketplace. Based on information provided by Seller, BizScout will prepare and publish the Business Listing, which may include: all accounts associated with Seller's business, including all associated accounts, content, data, customer lists, databases, files, and artwork; all general intangibles of Seller's Business; all instruments of Seller's business, including promissory notes, books and records, customer lists, email lists and other files related to the business; all letters of credit and letter-of-credit rights and supporting obligations; all inventory of Seller's business; all relevant domain names and associated domain name registrations; all intellectual property or proprietary rights; all prepaid expenses and subscriptions associated with Seller's business; and goodwill and the going concern value of Seller's business. Seller acknowledges that BizScout creates and publishes Business Listings on Seller's behalf and at Seller's direction based on information Seller provides. In its sole discretion, BizScout will approve or reject any Business Listing for listing on the Marketplace. BizScout reserves the right to reject, suspend or terminate any Business Listing for any reason or no reason at all.</li>
                     <li>Maintaining Listing Content. Seller is responsible for providing BizScout with all information, materials, images, and other content required to create and maintain Seller's Business Listing ("Seller-Provided Materials"). Seller shall provide complete and accurate Seller-Provided Materials in a timely manner to allow for BizScout's review and preparation of the Business Listing. Seller has an ongoing responsibility to promptly notify BizScout of any updates, corrections, or changes to the Seller-Provided Materials to ensure the Business Listing remains complete, accurate, and up-to-date. BizScout may notify Seller if issues are identified with the Business Listing or Seller's profile, and Seller agrees to promptly provide corrected or supplemental information to BizScout's reasonable satisfaction. Seller hereby authorizes BizScout to prepare, format, edit and publish the Business Listing based on the Seller-Provided Materials, including making modifications for formatting, presentation, clarity, or consistency purposes. BizScout also reserves the right, in its sole discretion, to remove or modify any Business Listing it deems to violate these Terms or for any other reason impacting platform integrity or presentation standards.</li>
                     <li>Pricing. Seller is solely responsible for setting a price for its listed Business Listing. To help Seller determine an appropriate price, BizScout makes certain valuation calculators available. You acknowledge and agree that any valuation produced by the calculators offered through the Services are an estimate only and must not be construed as or relied upon as a professional valuation. The valuation is generated by a mathematical model in reliance on industry data, without in-depth analysis and without regard to market conditions or features which may affect value and saleability.</li>
                     <li>Seller Representation and Warranties. In connection each Business Listing that Seller submits to the Marketplace, Seller represents and warrants to BizScout that (i) Seller owns the assets or is entitled to sell the assets listed; (ii) the business associated with any Business Listing submitted is an operating business in good standing under the laws of its jurisdiction; (iii) Seller is solely responsible for ensuring that its business operations associated with a submitted Business Listing materially comply with all applicable laws, rules, and regulations, including those related to advertising, marketing, data privacy and security, consumer protection, taxation, and employment (iv) there are no pending or, to Seller's knowledge, threatened government investigations, regulatory inquiries, or material private lawsuits against Seller or against the business associated with the Business Listing, that could reasonably be expected to adversely affect your ability to comply with these Terms or consummate a transaction; (v) Seller has all necessary intellectual property rights, title and interest in such assets; (vi) such assets are transferable to a buyer; (vii) any and all agreements with third parties applicable to a consummated transaction are transferable to the buyer; and (viii) BizScout shall have no responsibility or liability for any tax obligations in connection with a Consummated Transaction.

Seller acknowledges a continuous duty to maintain the accuracy of these representations. Accordingly, during the term of any Business Listing, Seller must immediately notify BizScout in writing of any material changes or new information that would cause Seller's representations to be untrue or misleading. BizScout reserves the right, in its sole discretion, to remove the Business Listing or suspend or terminate Seller's access to the Services upon receipt or discovery of such information.</li>
                     <li>Promoted Listing Fee. From time to time, BizScout may offer Sellers the option to purchase additional marketing or promotional services (“Promotion Services”) designed to increase the visibility of their listings within the BizScout Marketplace or through other digital marketing channels. These Promotion Services are entirely optional and are not required for participation in the Marketplace. If a Seller elects to use any Promotion Services, such services may be offered on a subscription basis with recurring monthly fees (“Promoted Listing Fee”). Details regarding the scope, pricing, and features of available Promotion Services will be set forth on the Marketplace and governed in accordance with these Terms</li>
                     <li>Marketing Fee. At the time of closing, sale, assignment or other consummation of a Business Listing by Seller, the Seller (jointly and severally with its Affiliates, successors, and assigns) shall pay BizScout a marketing fee (the “Marketing Fee”) in the amount and in accordance with the terms set forth on BizScout's then-current Marketing Fee schedule, which is published at www.bizscout.com/seller-pricing and is incorporated herein by reference. BizScout reserves the right to change the Marketing Fee, as detailed on its Marketing Fee schedule, at any time. BizScout will provide adequate notice of such changes before they become effective. The then-current Marketing Fee, as per the schedule in effect following such adequate notice, shall be applicable to any Consummated Transaction that occurs from the effective date specified in such notice forward, regardless of when acquisition discussions regarding the Business Listing began. Seller shall be liable for the Marketing Fee regardless of whether the relevant business transaction is completed directly through the BizScout Marketplace, by Seller outside the Marketplace, or through any of Seller’s Affiliates or a special purpose entity formed or used by or for the benefit of Seller. The Marketing Fee is payable in US dollars and is non-refundable. For the purpose of this Section: </li>
                </ol>
                  <h2 id="buyers" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Buyer Obligations, Representations and Warranties
                     </h2>
                <ol className="pl-5 flex flex-col items-start gap-2.5 list-decimal text-[16px] leading-[24px] font-light font-inter
                text-[#252423]">
                    <li>Non-Circumvention. Buyer shall not, directly or indirectly: (i) act in any manner intended to circumvent the Services or to facilitate the avoidance of the Marketing Fee payable by Seller to BizScout; or (ii) initiate contact or negotiations with a Seller regarding a Business Listing listed through the Services outside of the mechanisms provided by the Services, without BizScout's prior written consent.</li>
                    <li>Compliance. Upon BizScout's reasonable request, Buyer agrees to promptly provide information relating to any Business Listing accessed or acquired through the Services to enable BizScout to verify Buyer's and Seller’s compliance with and enforce these Terms.</li>
                    <li>Buyer Representations and Warranties. As a Buyer, and in addition to any other representations and warranties made by you in these Terms, you represent and warrant to BizScout that: (i) if you are an Organization, such Organization is duly organized, validly existing, and in good standing under the laws of its jurisdiction of organization, and possesses the full corporate or other organizational power and authority necessary to consummate any transaction for a Business Listing you pursue through the Services; (ii) there are no actions, suits, proceedings, or governmental investigations pending or, to your knowledge, threatened against you or your Organization that would reasonably be expected to materially and adversely affect your ability to perform your obligations under these Terms or your capacity to evaluate and consummate the acquisition of a Business Listing made available through the Services; (iii) you have, or will have at the time of making any offer or entering into any transaction for a Business Listing, access to sufficient funds or financing to fulfill your obligations with respect to such offer or transaction; and (iv) BizScout shall have no responsibility or liability for any tax obligations in connection with a Consummated Transaction</li>
                    <li>Survival. The obligations set forth in this Section shall survive the expiration or termination of these Terms.</li>
                </ol>
                <h2 id="market" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Marketplace Disclaimers, Informational Tools, and Third Party Services
                </h2>
                <ol className="pl-5 flex flex-col items-start gap-2.5 list-decimal text-[16px] leading-[24px] font-light font-inter
                text-[#252423]">
                    <li>Disclaimer of Warranties. PLEASE REVIEW VERY CAREFULLY THIS SECTION AND THE INTRODUCTORY SECTION “WHO WE ARE AND WHAT WE DO (AND WHAT WE DON’T DO,” AS THEY AFFECT YOUR RIGHTS AGAINST US AND REQUIRES YOU TO WAIVE CERTAIN REMEDIES AGAINST US.

Your use of the Services is at your sole risk. BizScout and its Affiliates, and each of their respective officers, directors, managers, members, employees, and contractors (“BizScout Parties”) make no representations or warranties concerning the Services, including without limitation regarding any content contained in or accessed through the Services, and shall not be responsible or liable for the accuracy, copyright compliance, or legality of material contained in or accessed through the Services or any claims, actions, suits, procedures, costs, expenses, damages or liabilities arising out of use of, or in any way related to your participation in the Services.

BizScout does not own or control any of the buyers, sellers or any of the sellers' businesses or assets listed on the Marketplace. The availability of any buyer or seller does not indicate an affiliation with or endorsement of the buyer or seller. Accordingly, BizScout does not provide any representations, warranties, or guarantees with respect to any buyer or seller or any business or assets of any seller. If you wish to obtain any representations, warranties, or guarantees with respect to any buyer, seller or sellers' assets or businesses, please consult directly with such buyer or seller.

THE SERVICES AND INFORMATION, INCLUDING BUSINESS LISTINGS, ARE PROVIDED BY BIZSCOUT ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR THAT USE OF THE SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, ERROR-FREE, OR FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. SOME STATES DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU.

YOU AFFIRM THAT BIZSCOUT PARTIES SHALL NOT BE LIABLE, UNDER ANY CIRCUMSTANCES, FOR ANY BREACH OF REPRESENTATION OR WARRANTY CLAIM THAT ARISE OUT OF ANY BUYER'S OR SELLER'S FAILURE TO HONOR ANY REPRESENTATION OR WARRANTY OBLIGATION TO YOU. </li>
                <li>Informational Tools. The Services may include access to certain informational tools and features, including ScoutSights (which provides operational insights), the Net Working Capital Calculator, the Deal Affordability Calculator, the Exit Value Calculator, the Valuation Multiple Analyzer, and the Buying Power Calculator (“Informational Tools”). You acknowledge and agree that any outputs, calculations, insights, or valuations provided by the Informational Tools are for informational purposes only. They do not constitute financial, valuation, investment, legal, tax, or other professional advice, and they are not, and cannot be, a substitute for advice or a formal valuation performed by qualified professionals. Many factors may affect the actual value or performance of a business, and BizScout makes no representations or warranties regarding the accuracy, completeness, or applicability of the information generated by the Informational Tools. You are encouraged in all instances to consult with appropriate qualified professionals for advice tailored to your specific circumstances.</li>
                <li>Linked Websites. The Services may contain links to third-party websites. Linked websites are not under BizScout’s control, and we are not responsible for their content. Please be sure to review the terms of use and privacy policy of any third-party services before you share any information with such third-party services.</li>
                </ol>
                <h2 id="fee" className="text-[30px] leading-[38px] font-lora font-medium text-[#252423] pt-6">
                    Compensation and Referral Fee Disclosure
                </h2>
                <ol className="pl-5 flex flex-col items-start gap-2.5 list-decimal text-[16px] leading-[24px] font-light font-inter
                text-[#252423]">
                    <li>Referral Partner Relationships. BizScout has entered into agreements with third-party service providers, including accounting firms, M&A insurance brokers, due diligence providers, and other professionals offering services related to business acquisitions (collectively, "Referral Partners"). BizScout may introduce you to Referral Partners through the Services or recommend their services in connection with a Business Listing or potential transaction. Referral Partners may be affiliates of BizScout.</li>
                    <li>Compensation Disclosure. BizScout receives compensation from Referral Partners when users engage their services. This compensation may take the form of referral fees, revenue-sharing payments, commissions, or other performance-based fees calculated as a percentage of the fees you pay to the Referral Partner. The specific compensation arrangement varies by Referral Partner. You acknowledge that this compensation structure creates a financial incentive for BizScout to recommend Referral Partners.</li>
                    <li>No Obligation; Independent Evaluation. You are under no obligation to engage any Referral Partner introduced by BizScout. You may obtain similar services from any provider of your choosing. BizScout encourages you to independently evaluate all service providers, compare pricing, and conduct your own due diligence before retaining any professional services.</li>
                    <li>No Endorsement or Warranty. BizScout's introduction of a Referral Partner does not constitute an endorsement, certification, or guarantee of the Referral Partner's qualifications, the quality of their services, or their suitability for your particular needs. BizScout makes no representations, warranties, or guarantees regarding any Referral Partner or the services they provide. BizScout is not a party to any agreement between you and a Referral Partner.</li>
                    <li>Disclaimer of Liability. BizScout is not responsible for disputes, liabilities, or losses arising from your engagement with any Referral Partner, including but not limited to errors, omissions, misrepresentations, or service failures by the Referral Partner. Any claims related to Referral Partner services must be directed to the Referral Partner.</li>
                </ol>
            </main>

        </section>
    )
}